// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addContact = `-- name: AddContact :one
WITH inserted AS (
    INSERT INTO contacts (user_from, user_to, chat_id, status)
    VALUES ($1, $2, $3, $4)
    ON CONFLICT (user_from, user_to) 
    DO UPDATE SET status = EXCLUDED.status
    RETURNING user_to, chat_id, status
)
SELECT 
    c.user_to AS id,
    c.chat_id AS chat_id,
    c.status AS status,
    u.name AS name
FROM inserted c
INNER JOIN users u ON c.user_to = u.id
`

type AddContactParams struct {
	UserFrom uuid.UUID `json:"user_from"`
	UserTo   uuid.UUID `json:"user_to"`
	ChatID   uuid.UUID `json:"chat_id"`
	Status   string    `json:"status"`
}

type AddContactRow struct {
	ID     uuid.UUID `json:"id"`
	ChatID uuid.UUID `json:"chat_id"`
	Status string    `json:"status"`
	Name   string    `json:"name"`
}

func (q *Queries) AddContact(ctx context.Context, arg AddContactParams) (AddContactRow, error) {
	row := q.db.QueryRow(ctx, addContact,
		arg.UserFrom,
		arg.UserTo,
		arg.ChatID,
		arg.Status,
	)
	var i AddContactRow
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Status,
		&i.Name,
	)
	return i, err
}

const delContact = `-- name: DelContact :exec
DELETE FROM contacts
WHERE user_from = $1 AND user_to = $2
`

type DelContactParams struct {
	UserFrom uuid.UUID `json:"user_from"`
	UserTo   uuid.UUID `json:"user_to"`
}

func (q *Queries) DelContact(ctx context.Context, arg DelContactParams) error {
	_, err := q.db.Exec(ctx, delContact, arg.UserFrom, arg.UserTo)
	return err
}

const delContacts = `-- name: DelContacts :exec
DELETE FROM contacts
WHERE user_to = $1
`

func (q *Queries) DelContacts(ctx context.Context, userTo uuid.UUID) error {
	_, err := q.db.Exec(ctx, delContacts, userTo)
	return err
}

const getContacts = `-- name: GetContacts :many
SELECT
    c.user_from AS id,
    c.status AS status,
    c.chat_id AS chat_id,
    u.name AS name
FROM contacts c
LEFT JOIN users u ON c.user_from = u.id
WHERE c.user_to = $1
`

type GetContactsRow struct {
	ID     uuid.UUID   `json:"id"`
	Status string      `json:"status"`
	ChatID uuid.UUID   `json:"chat_id"`
	Name   pgtype.Text `json:"name"`
}

func (q *Queries) GetContacts(ctx context.Context, userTo uuid.UUID) ([]GetContactsRow, error) {
	rows, err := q.db.Query(ctx, getContacts, userTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactsRow
	for rows.Next() {
		var i GetContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ChatID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContactRequest = `-- name: UpsertContactRequest :exec
INSERT INTO contacts (user_from, user_to, status, chat_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_from, user_to) 
DO UPDATE SET status = EXCLUDED.status
`

type UpsertContactRequestParams struct {
	UserFrom uuid.UUID `json:"user_from"`
	UserTo   uuid.UUID `json:"user_to"`
	Status   string    `json:"status"`
	ChatID   uuid.UUID `json:"chat_id"`
}

func (q *Queries) UpsertContactRequest(ctx context.Context, arg UpsertContactRequestParams) error {
	_, err := q.db.Exec(ctx, upsertContactRequest,
		arg.UserFrom,
		arg.UserTo,
		arg.Status,
		arg.ChatID,
	)
	return err
}
