// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addMessage = `-- name: AddMessage :exec
INSERT INTO messages (id, user_from, user_to, chat_id, content)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id, user_from, user_to) 
DO UPDATE SET content = EXCLUDED.content
`

type AddMessageParams struct {
	ID       uuid.UUID `json:"id"`
	UserFrom uuid.UUID `json:"user_from"`
	UserTo   uuid.UUID `json:"user_to"`
	ChatID   uuid.UUID `json:"chat_id"`
	Content  string    `json:"content"`
}

func (q *Queries) AddMessage(ctx context.Context, arg AddMessageParams) error {
	_, err := q.db.Exec(ctx, addMessage,
		arg.ID,
		arg.UserFrom,
		arg.UserTo,
		arg.ChatID,
		arg.Content,
	)
	return err
}

const addMessageStatus = `-- name: AddMessageStatus :exec
INSERT INTO message_statuses (id, user_from, user_to, chat_id, status)
VALUES ($1, $2, $3,  $4, $5)
ON CONFLICT (id, user_from, user_to) 
DO UPDATE SET status = EXCLUDED.status
`

type AddMessageStatusParams struct {
	ID       uuid.UUID `json:"id"`
	UserFrom uuid.UUID `json:"user_from"`
	UserTo   uuid.UUID `json:"user_to"`
	ChatID   uuid.UUID `json:"chat_id"`
	Status   string    `json:"status"`
}

func (q *Queries) AddMessageStatus(ctx context.Context, arg AddMessageStatusParams) error {
	_, err := q.db.Exec(ctx, addMessageStatus,
		arg.ID,
		arg.UserFrom,
		arg.UserTo,
		arg.ChatID,
		arg.Status,
	)
	return err
}

const delMessage = `-- name: DelMessage :exec
DELETE FROM messages 
WHERE user_to = $1
`

func (q *Queries) DelMessage(ctx context.Context, userTo uuid.UUID) error {
	_, err := q.db.Exec(ctx, delMessage, userTo)
	return err
}

const delMessageStatus = `-- name: DelMessageStatus :exec
DELETE FROM message_statuses 
WHERE user_to = $1
`

func (q *Queries) DelMessageStatus(ctx context.Context, userTo uuid.UUID) error {
	_, err := q.db.Exec(ctx, delMessageStatus, userTo)
	return err
}

const getMessageStatuses = `-- name: GetMessageStatuses :many
SELECT
    id as id,
    user_from as user_from,
    user_to as user_to,
    chat_id as chat_id,
    status as status
FROM message_statuses
WHERE user_to = $1
`

type GetMessageStatusesRow struct {
	ID       uuid.UUID `json:"id"`
	UserFrom uuid.UUID `json:"user_from"`
	UserTo   uuid.UUID `json:"user_to"`
	ChatID   uuid.UUID `json:"chat_id"`
	Status   string    `json:"status"`
}

func (q *Queries) GetMessageStatuses(ctx context.Context, userTo uuid.UUID) ([]GetMessageStatusesRow, error) {
	rows, err := q.db.Query(ctx, getMessageStatuses, userTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessageStatusesRow
	for rows.Next() {
		var i GetMessageStatusesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserFrom,
			&i.UserTo,
			&i.ChatID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessages = `-- name: GetMessages :many
SELECT
    id as id,
    user_from as user_from,
    user_to as user_to,
    chat_id as chat_id,
    content as content
FROM messages
WHERE user_to = $1
`

type GetMessagesRow struct {
	ID       uuid.UUID `json:"id"`
	UserFrom uuid.UUID `json:"user_from"`
	UserTo   uuid.UUID `json:"user_to"`
	ChatID   uuid.UUID `json:"chat_id"`
	Content  string    `json:"content"`
}

func (q *Queries) GetMessages(ctx context.Context, userTo uuid.UUID) ([]GetMessagesRow, error) {
	rows, err := q.db.Query(ctx, getMessages, userTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesRow
	for rows.Next() {
		var i GetMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserFrom,
			&i.UserTo,
			&i.ChatID,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
