// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push_notification.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addPush = `-- name: AddPush :exec
INSERT INTO push_notifications (user_id, expo_token, user_lang)
VALUES ($1, $2, $3)
`

type AddPushParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ExpoToken string    `json:"expo_token"`
	UserLang  string    `json:"user_lang"`
}

func (q *Queries) AddPush(ctx context.Context, arg AddPushParams) error {
	_, err := q.db.Exec(ctx, addPush, arg.UserID, arg.ExpoToken, arg.UserLang)
	return err
}

const getPush = `-- name: GetPush :many
SELECT
    p.user_id AS user_id,
    p.expo_token AS expo_token,
    p.user_lang AS user_lang
FROM push_notifications AS p
WHERE p.user_id = $1
`

type GetPushRow struct {
	UserID    uuid.UUID `json:"user_id"`
	ExpoToken string    `json:"expo_token"`
	UserLang  string    `json:"user_lang"`
}

func (q *Queries) GetPush(ctx context.Context, userID uuid.UUID) ([]GetPushRow, error) {
	rows, err := q.db.Query(ctx, getPush, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPushRow
	for rows.Next() {
		var i GetPushRow
		if err := rows.Scan(&i.UserID, &i.ExpoToken, &i.UserLang); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
